### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by mnkykm** [Tzetachi/Computer-Modern-Unicode-Oesol#1]
안녕하세요, CMUO 폰트 제작 협업에 초대받은 김민규입니다.
@Tzetachi 님께서 현재 생각하시는 CMUO 폰트 제작에 향후 과제들과, 프로젝트의 범위를 어떻게 잡고 싶으신지 의견 듣고 싶습니다.
저는 단기적으로는 CMUO 의 미세조정(커널 등), 이탤릭, 산세리프체 개발, 장기적으로는 해방 전후시기의 각종 한글 개량 시도의 전산화, 〈조선어 신 철자법〉과 같은 모아쓰기 구현 시도 등이 가능할 것 같습니다. 
커뮤니케이션 채널은 어떻게 구축하는 게 좋을까요? 여기 레포의 Issues 에 스레드 형식으로 의견개진하며, Wiki에 로드맵 등을 작성해도 좋을 것 같고, 불편하지 않으시다면 Slack 이나 Telegram 등과 같은 메시징 서비스로 채팅을 하는 것도 어떨까합니다. 편하신 대로 의견 주세요.
감사합니다.

**Comment by Tzetachi** [comment]
초대에 응해 주셔서 감사합니다. 우선 대체적으로 @minkyuxyz 님께서 제시하신 사항들 정도를 생각하고 있습니다. 추가하고 싶은 것은 지금으로서는 수학용 폰트 정도가 있겠네요. 우선 CMUO 프로젝트에서는 외솔식 풀어쓰기만을 다룰 예정이고, 신 철자법 자모나 그 외의 시도들의 구현은 새로운 프로젝트로 시작하는 것이 좋을 듯합니다.
커뮤니케이션 역시 말씀하신 대로 GitHub를 적극 활용하면서 조금 더 세세한 사항들은 Slack을 통해 연락하면 좋을 것 같습니다.

**Comment by Tzetachi** [comment]
이메일 주소 남겨 주시면 Slack 초대드리겠습니다.

**Comment by mnkykm** [comment]
minkyuxyz@gmail.com 입니다.
Github Project 도 하나 파서 main 레포에 brainstorming 하면 좋겠습니다. 여기 CMUO 레포는 그대로 두고요.
