### ISSUE TITLE
이 글꼴을 칠 수 있는 웹 넣개(입력기)를 만들어봤습니다.

### ISSUE THREAD

**Issue by ThisIsPIRI** [Tzetachi/Computer-Modern-Unicode-Oesol#2]
https://gitlab.com/phost/web-tools/-/tree/master/Amuneoh
https://phost.gitlab.io/wt/am
웹으로도 외솔 풀어쓰기를 쓸 수 있도록 단촐하게 만들어 봤습니다.

**Comment by Tzetachi** [comment]
> https://gitlab.com/phost/web-tools/-/tree/master/Amuneoh
> 
> https://phost.gitlab.io/wt/am
> 
> 웹으로도 외솔 풀어쓰기를 쓸 수 있도록 단촐하게 만들어 봤습니다.

답이 늦어 죄송합니다. 우선 외솔 글꼴에 관심 가져 주시고 이렇게 웹 입력기도 만들어 주셔서 감사합니다. 사실 작년 초까지만 하더라도 CMUO에 몇 가지 글꼴을 더 추가하고 그 밖의 역사적으로 유의미한 여러 한글 개량안들을 틈틈이 조금씩이나마 구현해 나갈 요량으로 함께 작업하실 분도 구하고 했었는데, 얼마 되지도 못해 제 사정 때문에, 그분께는 죄송스럽게도 제대로 말씀도 못 드린 채, 마지막 commit 이후로 그냥 방치해 둔 상태였습니다. 그렇게 전혀 신경을 못 써 아쉬워하던 차에 이렇게 관심과 도움을 주시니 대단히 감사할 따름입니다.

P.S. 한 가지 덧붙여 말씀드리자면, 웹 입력기에 적용하신 Oesol Serif 글꼴은 제가 그야말로 아무것도 모르던 상태로 무작정 만들기 시작한 것이라 완성도나 자형의 미려함에서 나중에 새로 제작한 CMUO에 비해 많이 부족합니다. 그래서 제작하신 «아무넣» 입력기에 CMUO가 적용된다면 더욱 바람직하지 않을까 생각합니다.

**Comment by ThisIsPIRI** [comment]
답장 고맙습니다. 제 입맛에는 Oesol이 더 맞아서(ㅑ와 ㅕ의 부드러운 끝머리, ㅊ과 ㅎ의 넓은 윗점 들) 그걸 썼는데 겨를이 생기면 CMUO도 더불어 쓸 수 있도록 더해 보겠습니다.

**Comment by ThisIsPIRI** [comment]
말씀하신 대로 [아무넣](https://phost.gitlab.io/wt/am)에 CMUO를 씌웠습니다.

**Comment by Tzetachi** [comment]
잊지 않고 계속 관심 가져 주셔서 감사합니다. 지난번에 진작 README 문서를 고쳐야 했는데, 정작 제가 잊고 있다가 이제야 추가하게 되어 죄송합니다. 다른 준비 없이 쉽게 웹에서 두 글꼴을 바로 사용해 볼 수 있게 되어 기쁩니다.
