### ISSUE TITLE
범용 플랫폼에서 CMUO를 사용할 수 있도록 조처하였습니다.

### ISSUE THREAD

**Issue by oysol** [Tzetachi/Computer-Modern-Unicode-Oesol#4]
첫 번째로, 공개 소스 입력기인 Keyman으로 입력할 수 있게 하였습니다.
https://github.com/oysol/Oesol-Keyman
현재는 리눅스 정도만 공식 지원하지만 추후, 모바일 기기로까지 지원 확장할 것입니다.

두 번째로, 이맥스에서 예일 로마자 표기법으로 글을 입력하면 CMUO에 맞게 변환해주는 방식의 함수를 만들었습니다.
https://github.com/oysol/oysolscript

좋은 글꼴 만들어주셔서 감사드립니다.

**Comment by Tzetachi** [comment]
CMUO에 관심 갖고 기여해 주셔서 감사합니다. 덕분에 이제는 여러 플랫폼에서 CMUO를 사용해서 입력하는 것이 수월해질 것 같습니다. 특히 예일식 표기법과 대응하는 방안도 생각만 하고 실천을 하지 못하던 것인데, 이렇게 직접 만들어 주셔서 기쁘게 생각합니다. 날씨가 많이 더운데 아무쪼록 건강에 유의하시길 바랍니다.
